--DDL
--DEPT2 TALBE 생성
CREATE TABLE DEPT2
(DEPTNO NUMBER(2), NAME VARCHAR2(14), LOC VARCHAR2(13));

SELECT * FROM TAB;

--CONSTRAINT 제약조건
--PRIMARY KEY 생성
--PK_DEPT라는 이름의 제약조건 - NULL 일수 없고 중복될 수 없다.
ALTER TABLE DEPT2
ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO);

DESC DEPT2 -- 구성확인

SELECT * FROM DEPT2;
--DML
INSERT INTO DEPT2 (DEPTNO, NAME, LOC) VALUES (10, 'IT', 'SEOUL');
INSERT INTO DEPT2 (DEPTNO, NAME, LOC) VALUES (20, 'HR', 'SEOUL');
INSERT INTO DEPT2 (DEPTNO, NAME, LOC) VALUES (30, 'PU', 'BUSAN');

--NUMBER(7,2) -> 전체숫자 자리수는 7자리이고 소숫점 아래의 숫자는 24ㅐ까지가능 EX) 12345.67
CREATE TABLE EMP2
(EMPNO NUMBER(4), ENAME VARCHAR2(10), JOB VARCHAR2(9), MGR NUMBER(4), HIREDATE DATE, SAL NUMBER(7,2), COMM NUMBER(7,2), DEPTNO NUMBER(2));

ALTER TABLE EMP2 ADD CONSTRAINT EMP2_EMPNO PRIMARY KEY (EMPNO);
SELECT * FROM EMP2;

ALTER TABLE EMP2 DROP CONSTRAINT EMP2_EMPNO;
ALTER TABLE EMP2 ADD CONSTRAINT PK_EMP PRIMARY KEY (EMPNO);

ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD';

INSERT INTO EMP2
VALUES (200, 'KIM', 'IT_MGR', NULL, '2005-06-20', 8000, NULL, NULL);

--FOREIGN KEY 컬럼이 되면 FOREIGN KEY 컬럼에는 중복되는 데이타가 들어올수 있고 NULL인 상태도 될 수 있다.
ALTER TABLE EMP2
ADD CONSTRAINT FK_DEPTNO FOREIGN KEY(DEPTNO) REFERENCES DEPT2(DEPTNO);
SELECT * FROM EMP2;
INSERT INTO EMP2 VALUES (201, 'LEE', 'IT_REP', 200, '2006-12-20', 6000, NULL, 10);
INSERT INTO EMP2 VALUES (202, 'PARK', 'HR_REP', 203, '2007-10-20', 9000, NULL, 20);
INSERT INTO EMP2 VALUES (203, 'OH', 'HR_MGR', 200, '2010-7-20', 10000, NULL, 20);
INSERT INTO EMP2 VALUES (204, 'NOH', 'PU_MGR', 203, '2012-09-20', 12000, 0.6, 30);
INSERT INTO EMP2 VALUES (205, 'SEO', 'PR_REP', 204, '2010-03-20', 7000, 0.3, 30);

-- FOREIGN KEY 컬럼이 생성이 되면 FOREIGN KEY COLUMN과 연결되어 있는 부서테이블의 부서정보를 삭제하고자 할 때 
-- 삭제하려고하는 부서의 관련된 사원 정보가 사원 테이블에 남아 있는 경우에 부서테이블의 부서정보를 삭제하지 못하게 된다.

SELECT * FROM DEPT2;
SELECT * FROM EMP2;

--못지운다.
DELETE FROM DEPT2 WHERE DEPTNO=30;

--관련된 정보를 NULL로 만들어주면 삭제가능
UPDATE EMP2 SET DEPTNO=NULL WHERE DEPTNO=30;
DELETE FROM DEPT2 WHERE DEPTNO=30;

--FOREIGN KEY가 생성되어있는 테이블에서 DEPT2테이블에 없는 부서를 새로 생성하는 것 불가능.
INSERT INTO EMP2 VALUES (206, 'SIM', 'PU_REP', 203, '2013-4-10', 7000, NULL, 60);  -- (X)
INSERT INTO DEPT2 (DEPTNO, NAME, LOC) VALUES (60, 'PU', 'BUSAN'); -- 60부서를 생성후 에는 위에 것 가능

* CONSTRAINT  제약조건 종류
1. PRIMARY KEY
2. FOREIGN KEY
3. UNIQUE
4. NOT NULL
5. CHECK

-- 3.UNIQUE
CREATE TABLE SAMPLEA (NAME VARCHAR2(20) CONSTRAINT SAMPLEA_NAME_UK UNIQUE);
INSERT INTO SAMPLEA VALUES ('A');
SELECT * FROM SAMPLEA;
INSERT INTO SAMPLEA VALUES ('A'); -- 같은 값 삽입 안됨.

--4. NOT NULL
CREATE TABLE SAMPLEB (NAME VARCHAR2(20) CONSTRAINT SAMPLEB NOT NULL);
INSERT INTO SAMPLEB VALUES (NULL); -- NULL 삽입 x

--5. CHECK
CREATE TABLE SAMPLEC (NAME VARCHAR2(20), SALARY NUMBER(10),
                                            CONSTRAINT SAMPLEC_1 CHECK (NAME LIKE '%a%'), -- NAME컬럼에는 소문자a가 포함
                                            CONSTRAINT SAMPLEC_2 CHECK (SALARY BETWEEN 1000 AND 5000));  --SALARY컬럼에서는 1000에서 5000사이
INSERT INTO SAMPLEC VALUES ('ABC', 3000);
INSERT INTO SAMPLEC VALUES ('aBC', 6000);
SELECT * FROM SAMPLEC;

--데이터 딕셔너리 (DATA DICTIONARY) : 제약조건 찾기
DESC USER_CONSTRAINTS

SELECT * FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'SAMPLEC_1';





